version: '3.0'

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: DockerfileServer
    env_file:
      - ./server/.development.env
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    ports:
      - "5050:5050"
      - "9229:9229"
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - ./server/.development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: DockerfileClient
    ports:
      - "1111:1111"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
volumes:
  pgdata: